### ISSUE TITLE
Rebase 'export' branch on latest upstream Hollo main

### ISSUE THREAD

**Issue by dmitrizagidulin** [did-coop/activitypub-export#18]
As we're working on the export/import functionality, the upstream Hollo fork continues to get updates. So, for example, we're currently 177 commits behind the upstream fork.

This issue is to rebase on latest upstream main. So:

First, add upstream as a remote, so you can synchronize with them:

```
git remote add upstream https://github.com/dahlia/hollo.git
```
Next, fetch the latest commits from upstream:
```
git fetch upstream
```

Assuming you're on the `account-export` branch (if not, `git checkout account-export`):

```
git rebase upstream/main
```

This will fast-forward your current `account-export` branch and rebase it to be on top of the latest `main` from the upstream.

If you get a lot of merge conflicts and are unable to resolve them, ping @dmitrizagidulin and he'll walk you through it.

**Comment by 0marSalah** [comment]
Got this message after resolve all conflicts and want to sync changes

> git pull --tags origin account-export
From github.com:did-coop/hollo
 * branch            account-export -> FETCH_HEAD
hint: Diverging branches can't be fast-forwarded, you need to either:
hint:
hint: 	git merge --no-ff
hint:
hint: or:
hint:
hint: 	git rebase
hint:
hint: Disable this message with "git config advice.diverging false"
fatal: Not possible to fast-forward, aborting.

❯ git status              
On branch account-export
Your branch and 'origin/account-export' have diverged,
and have 107 and 24 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

nothing to commit, working tree clean

**Comment by 0marSalah** [comment]
update: i have just end the rebasing process, account export and media export is working fine without any conflicts :)

**Comment by 0marSalah** [comment]
done and assigned to @dmitrizagidulin to review.

**Comment by 0marSalah** [comment]
account-export PR link https://github.com/dahlia/hollo/pull/33

**Comment by dmitrizagidulin** [comment]
Rebased for the moment, but two rebase conflicts still exist, will deal with them later.
